#!/usr/bin/env bash

wget --no-check-certificate https://github.com/smok-serwis/pojeb/archive/master.tar.gz
tar xvf master.tar.gz
cd pojeb-master
sudo bash install.sh
cd ..
rm -rf master.tar.gz pojeb-master
